[package]
name = "sito-wireguard-vpn"
version = "0.3.0"
description = "Cliente WireGuard plug and play para macOS"
authors = ["sito8943"]
edition = "2021"

[lib]
name = "sito_wireguard_vpn_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
